import Head from "next/head";
import Link from "next/link";

export default function Projects({ posts }) {
  return (
    <>
      <Head>
        <title>Samuel Khongthaw</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="flex flex-col bg-black sticky top-0">
        <div
          id="navbar"
          style={{ fontFamily: "Mukta", fontWeight: "600" }}
          className="tracking-wider sticky top-0 z-10 backdrop-filter backdrop-blur-md border-b border-gray-200 bg-opacity-30 flex justify-end font-bold items-center bg-black h-14  pr-2 md:pr-4"
        >
          <Link href={".."}>
            <div className="pr-4 md:pr-4 text-neutral-400 text-sm cursor-pointer">
              Home
            </div>
          </Link>
          <div className="pr-4 md:pr-4 text-neutral-400 text-sm cursor-pointer">
            Blogs
          </div>
          <div className="text-neutral-400 text-sm cursor-pointer">Gallery</div>
        </div>
        <div className="flex flex-col -z-10 items-center pt-10">
          <div className="max-w-2xl flex flex-col items-center">
            <div
              style={{ fontFamily: "Mukta", fontWeight: "400" }}
              className="text-center tracking-wider text-xl md:text-xl pl-4 container text-neutral-300"
            >
              Some personal/team projects.
            </div>
            <div
              style={{ fontFamily: "Mukta", fontWeight: "400" }}
              className="bg-neutral-900 w-max mt-10 max-w-xl h-max p-10 rounded-lg tracking-wider text-neutral-300 flex flex-col"
            >
              <div>
                A timer based on the Pomodoro technique. Built using Flutter for
                Android.
              </div>
              <div className="pt-4 text-neutral-500">Source code:</div>
              <div className="pt-4 text-neutral-500">Play Store:</div>
            </div>
            <div
              style={{ fontFamily: "Mukta", fontWeight: "400" }}
              className="bg-neutral-900 w-max max-w-xl mt-2 h-max p-10 rounded-lg tracking-wider text-neutral-300 flex flex-col"
            >
              <div>
                An attendance management software built using Next.js and
                TailwindCSS on the frontend.
              </div>
              <div className="pt-4 text-neutral-500">Source code:</div>
              <div className="pt-4 text-neutral-500">Play Store:</div>
            </div>
            <div
              style={{ fontFamily: "Mukta", fontWeight: "400" }}
              className="bg-neutral-900 w-max max-w-xl mt-2 h-max p-10 rounded-lg tracking-wider text-neutral-300 flex flex-col"
            >
              <div>
                An attendance management software built using Next.js and
                TailwindCSS on the frontend.
              </div>
              <div className="pt-4 text-neutral-500">Source code:</div>
              <div className="pt-4 text-neutral-500">Play Store:</div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
